# Generated by Django 5.0.3 on 2024-06-06 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("bn_name", models.CharField(max_length=100)),
                ("total_district", models.IntegerField(default=0)),
                ("total_upazila", models.IntegerField(default=0)),
                ("area", models.FloatField(default=0.0)),
                ("population", models.IntegerField(default=0)),
                ("density", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("bn_name", models.CharField(max_length=100)),
                ("lat", models.FloatField(default=0.0)),
                ("lon", models.FloatField(default=0.0)),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="districts",
                        to="tour_planner.division",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TouristPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("bn_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tourist_places",
                        to="tour_planner.district",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeatherUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("min_temp", models.FloatField(default=0.0)),
                ("max_temp", models.FloatField(default=0.0)),
                ("rain", models.FloatField(default=0.0)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_updates",
                        to="tour_planner.district",
                    ),
                ),
            ],
        ),
    ]
